name: "\U0001F680 Guide request"
description: Submit a proposal/request for a new production guide
labels: [ "guide" ]
body:
  - type: textarea
    id: guide-request
    validations:
      required: true
    attributes:
      label: Guide request
      description: |
        A clear and concise description of the guide you'd like to see. Please provide a link to any relevant resources in case they exist.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Please outline the motivation for the proposal. Is your request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.

  - type: textarea
    id: contribution
    validations:
      required: true
    attributes:
      label: Your contribution
      description: |
        Is there any way that you could help, e.g. by submitting a PR for this guide?